name: Test Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show files
        run: ls

      - name: Print message
        run: echo "Code is ready"